config/routes.rb
Rails.application.routes.draw do
  get 'finders/finder'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get 'finder' => "finders#finder"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}


	def self.looks(searches, words)
	  if searches == "perfect_match"
	    @book = Book.where("title LIKE ?", "#{words}")
	  elsif searches == "partial_match"
	    @book = Book.where("title LIKE ?", "%#{words}%")
	  elsif searches == "forward_match"
	    @book = Book.where("title LIKE ?", "#{words}%")
	  elsif searches == "backward_match"
	    @book = Book.where("title LIKE ?", "%#{words}")
	  end
	end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50 }

  attachment :profile_image, destroy: false

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name:"Relationship", foreign_key:"follower_id",dependent: :destroy
  has_many :passive_relationships, class_name:"Relationship", foreign_key:"followed_id",dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :followings, through: :active_relationships, source: :followed

  def followed_by?(user)
  passive_relationships.find_by(follower_id: user.id).present?
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE ?", "%#{words}")
    end

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @create_book = Book.new
    @post_comment = PostComment.new
  end


  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])

    unless current_user == @book.user
    redirect_to books_path
    end

  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  # def destroy
  #   @book = Book.find(params[:id])
  #   @book.destroy
  #   redirect_to books_path
  # end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book_fav = Book.find(params[:book_id])
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  end

  def destroy
    @book_fav = Book.find(params[:book_id])
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
  end

end

app/controllers/finders_controller.rb
class FindersController < ApplicationController
  def finder

    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    elsif @range == "Book"
      @books = Book.looks(params[:search], params[:word])
    end

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])

    @post_comment = PostComment.new
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:id])
    PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def index
  end

  def show
  end

  def create
    follow = current_user.active_relationships.build(followed_id: params[:user_id])
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    follow = current_user.active_relationships.find_by(followed_id: params[:user_id])
    follow.destroy
    redirect_back(fallback_location: root_path)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @users = current_user
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @booking = Book.all
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/finders_helper.rb
module FindersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class=<%= "favorite-btn_#{book.id}" %>>
            <%= render 'favorites/favorite-btn', book: book %>
        </td>
        <td>
          <p>コメント数：<%= book.post_comments.count %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user, book: @book %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @create_book %>
    </div>

    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td>
          <td class=<%= "favorite-btn_#{@book.id}" %>>
            <%= render 'favorites/favorite-btn', book: @book %>
          </td>
          <td>
            <p>コメント数：<%= @book.post_comments.count %></p>
          </td>

          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %></td>
          <% end %>
         </tr>
      </table>

      <div class =<%= "post_comments_" + @book.id.to_s %>>
        <%= render 'post_comments/post_comment', book: @book %>
      </div>

      <div class="new-comment">
        <%= form_with(model:[@book, @post_comment], remote: true) do |f| %>
          <%= f.text_area :comment, rows:'8', cols:'90',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>


    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <p><%= link_to book_favorites_path(book), method: :delete, remote: true do %>♥<%= book.favorites.count %> いいね<% end %></p>
<% else %>
  <p><%= link_to book_favorites_path(book), method: :post, remote: true do %>♡<%= book.favorites.count %> いいね<% end %></p>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn_"+<%=@book_fav.id%>).html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book_fav}) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn_"+<%=@book_fav.id%>).html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book_fav}) %>");

app/views/finders/_finder.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-8 offset-md-4'>
      <%= form_with url: finder_path, method: :get, local: :true do |f| %>
        <%= f.select :range, options_for_select([['User'], ['Book']]) %>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"], ["前方一致","forward_match"], ["後方一致","backward_match"]])%>
        <%= f.text_field :word %>
        <%= f.submit "検索" %>
      <% end %>
    </div>
  </div>
</div>

app/views/finders/finder.html.erb
<table class='table'>
  <tbody>
    <% if @range == "User" %>
      <h1>Users search for "test"</h1>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.followings.count %></td>
            <td>フォロワー数 : <%= user.followers.count %></td>
          </tr>
        <% end %>
    <% elsif @range == "Book" %>
      <h1>Books search for "test"</h1>
        <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
          <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %><td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/post_comments/_post_comment.html.erb
<div class="comments">
  <% book.post_comments.each do |post_comment| %>
      <%= image_tag("no-image-icon.jpg") %>
      <%= post_comment.user.name %>
    <% if post_comment.user == current_user %>
      <%= link_to "Delete", book_post_comment_path(post_comment.book, post_comment), method: :delete, class: 'btn btn-danger' %>
    <% end %>
      <p><%= post_comment.comment %></p>
  <% end %>
</div>

app/views/post_comments/create.js.erb
$(".post_comments_"+<%=@book.id%>).html("<%= escape_javascript(render partial: 'post_comments/post_comment', locals: {book: @book}) %>");
$(post_comment_comment).val('');

app/views/post_comments/destroy.js.erb
$(".post_comments_"+<%=@book_fav.id%>).html("<%= escape_javascript(render partial: 'post_comments/post_comment', locals: {book: @book}) %>");

app/views/users/_follow_form.html.erb
 <% if current_user != user %>
        <% if user. followed_by?(current_user) %>
            <p><%=link_to "フォローを外す", user_relationships_path(user.id), class: 'btn btn-danger', method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), class: 'btn btn-success', method: :post %></p>
        <% end %>
    <% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          フォロー数：<%= user.followings.count %>
        </td>
        <td>
          フォロワー数 : <%= user.followers.count %>
        </td>

        <td>
          <% if current_user != user %>
            <% if user. followed_by?(current_user) %>
              <p><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></p>
            <% else %>
              <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follow</th>
    <th><%=link_to user.followings.count, follows_user_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%=link_to user.followers.count, followers_user_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <h1>Follow Users</h1>
    <% @users.each do |user| %>
    <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          フォロー数：<%= user.followings.count %>
        </td>
        <td>
          フォロワー数 : <%= user.followers.count %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <h1>Follow Users</h1>
    <% @users.each do |user| %>
    <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          フォロー数：<%= user.followings.count %>
        </td>
        <td>
          フォロワー数 : <%= user.followers.count %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
        <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <%= render 'index',users: @users %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <%= render 'follow_form', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
          <%= render 'books/index',books: @booking %>
      </div>
    </div>
  </div>
</div>